AllCops:
  NewCops: enable

Lint/EmptyClass:
  Enabled: true
  AllowComments: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'Rakefile'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
